// examples/react-vite-pwa/src/App.tsx
import { useState } from "react";
import "./App.css";
import ViteExample from "./EvoluDemo.tsx";
import PWABadge from "./PWABadge.tsx";
import reactLogo from "./assets/react.svg";
import appLogo from "/favicon.svg";

function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={appLogo} className="logo" alt="vite-react-pwa logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>vite-react-pwa</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <div
        style={{
          textAlign: "left",
        }}
      >
        <ViteExample />
      </div>
      <PWABadge />
    </>
  );
}

export default App;

// examples/vue-vite-pwa/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
import PWABadge from './components/PWABadge.vue'
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/favicon.svg" class="logo" alt="vue-vite-pwa logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="vue-vite-pwa" />
  <PWABadge />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
