// packages/evolu-solid/src/useSyncState.ts
import type { Accessor } from "solid-js";;
import { SyncState } from "@evolu/common";
import { useEvolu } from "./useEvolu.js";
import { useSyncExternalStore } from "./useSyncExternalStore.js";

/** Subscribe to {@link SyncState} changes. */
export const useSyncState = (): Accessor<SyncState> => {
  const evolu = useEvolu();
  return useSyncExternalStore(evolu.subscribeSyncState, () =>
      evolu.getSyncState());
};

// packages/evolu-common-react/src/useSyncState.ts
import { SyncState, initialSyncState } from "@evolu/common";
import { useSyncExternalStore } from "react";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link SyncState} changes. */
export const useSyncState = (): SyncState => {
  const evolu = useEvolu();
  return useSyncExternalStore(
    evolu.subscribeSyncState,
    evolu.getSyncState,
    () => initialSyncState,
  );
};
