// packages/evolu-solid/src/useSyncState.ts
import type { Accessor } from "solid-js";;
import { SyncState } from "@evolu/common";
import { useEvolu } from "./useEvolu.js";
import { useSyncExternalStore } from "./useSyncExternalStore.js";

/** Subscribe to {@link SyncState} changes. */
export const useSyncState = (): Accessor<SyncState> => {
  const evolu = useEvolu();
  return useSyncExternalStore(evolu.subscribeSyncState, () =>
      evolu.getSyncState());
};

// packages/react/src/local-first/useSyncState.ts
import type { SyncState } from "@evolu/common/local-first";
import { use } from "react";
import { EvoluContext } from "./EvoluContext.js";

/** Subscribe to {@link SyncState} changes. */
export const useSyncState = (): SyncState => {
  const _evolu = use(EvoluContext);
  // return useSyncExternalStore(
  //   evolu.subscribeSyncState,
  //   evolu.getSyncState,
  //   () => initialSyncState,
  // );
  throw new Error("TODO");
};
