// packages/react/src/EvoluProvider.tsx
"use client";

import { Evolu } from "@evolu/common/evolu";
import { ReactNode } from "react";
import { EvoluContext } from "./EvoluContext.js";

export const EvoluProvider = ({
  children,
  value,
}: {
  readonly children?: ReactNode | undefined;
  readonly value: Evolu<any>;
}): React.ReactElement => <EvoluContext value={value}>{children}</EvoluContext>;

// packages/evolu-solid/src/EvoluProvider.tsx
"use client";

import { Evolu, DatabaseSchema } from "@evolu/common";
import { EvoluContext } from "./EvoluContext.js";
import type { JSX } from "solid-js";

export const EvoluProvider = <S extends DatabaseSchema>({
  children,
  value,
}: {
  readonly children?: JSX.Element | undefined;
  readonly value: Evolu<S>;
}): JSX.Element => {
  return (
    <EvoluContext.Provider value={value as Evolu}>
      {children}
    </EvoluContext.Provider>
  );
};
