// packages/evolu-common-react/src/useEvoluError.ts
import * as O from "effect/Option";
import { pipe } from "effect/Function";
import { EvoluError } from "@evolu/common";
import { useSyncExternalStore } from "react";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link EvoluError} changes. */
export const useEvoluError = (): EvoluError | null => {
  const evolu = useEvolu();
  const oStore = useSyncExternalStore(
    evolu.subscribeError,
    evolu.getError,
    (): O.Option<EvoluError> => O.none(),
  );

  return pipe(oStore, O.getOrNull); 
};

// packages/evolu-solid/src/useEvoluError.ts
import type { Accessor } from "solid-js";
import * as O from "effect/Option";
import { pipe } from "effect/Function";
import { EvoluError } from "@evolu/common";
import { useEvolu } from "./useEvolu.js";
import { useSyncExternalStore } from "./useSyncExternalStore.js";

/** Subscribe to {@link Owner} changes. */
export const useEvoluError = (): Accessor<EvoluError | null> => {
  const evolu = useEvolu();
  return pipe(
    useSyncExternalStore(evolu.subscribeError, evolu.getError),
    (v) => () => O.getOrNull(v()),
  );
};
