// packages/react/src/useEvoluError.ts
import { lazyNull, type EvoluError } from "@evolu/common";
import { useSyncExternalStore } from "react";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link EvoluError} changes. */
export const useEvoluError = (): EvoluError | null => {
  const evolu = useEvolu();
  return useSyncExternalStore(evolu.subscribeError, evolu.getError, lazyNull);
};

// packages/evolu-solid/src/useEvoluError.ts
import type { Accessor } from "solid-js";
import * as O from "effect/Option";
import { pipe } from "effect/Function";
import { EvoluError } from "@evolu/common";
import { useEvolu } from "./useEvolu.js";
import { useSyncExternalStore } from "./useSyncExternalStore.js";

/** Subscribe to {@link Owner} changes. */
export const useEvoluError = (): Accessor<EvoluError | null> => {
  const evolu = useEvolu();
  return pipe(
    useSyncExternalStore(evolu.subscribeError, evolu.getError),
    (v) => () => v()
  );
};
