// packages/evolu-common-react/src/useOwner.ts
import * as O from "effect/Option";
import { Owner } from "@evolu/common";
import { pipe } from "effect/Function";
import { useSyncExternalStore } from "react";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link Owner} changes. */
export const useOwner = (): Owner | null => {
  const evolu = useEvolu();
  const oStore = useSyncExternalStore(
    evolu.subscribeOwner,
    evolu.getOwner,
    (): O.Option<Owner> => O.none(),
  );

  return pipe(oStore, O.getOrNull);
};

// packages/evolu-solid/src/useOwner.ts
import type { Accessor } from "solid-js";
import * as O from "effect/Option";
import { pipe } from "effect/Function";
import { Owner } from "@evolu/common";
import { useEvolu } from "./useEvolu.js";
import { useSyncExternalStore } from "./useSyncExternalStore.js";

/** Subscribe to {@link Owner} changes. */
export const useOwner = (): Accessor<Owner | null> => {
  const evolu = useEvolu();
  return pipe(
    useSyncExternalStore(evolu.subscribeOwner, evolu.getOwner),
    (v) => () => O.getOrNull(v()),
  );
};
