// packages/react/src/local-first/useQuerySubscription.ts
import { lazyVoid } from "@evolu/common";
import {
  type Query,
  type QueryRows,
  type Row,
  emptyRows,
} from "@evolu/common/local-first";
import { use, useEffect, useMemo, useRef, useSyncExternalStore } from "react";
import { EvoluContext } from "./EvoluContext.js";

/** Subscribe to {@link Query} {@link QueryRows} changes. */
export const useQuerySubscription = <R extends Row>(
  query: Query<R>,
  options: Partial<{
    /**
     * Only subscribe and get the current value once. Subscribed query will not
     * invoke React Suspense after a mutation.
     */
    readonly once: boolean;
  }> = {},
): QueryRows<R> => {
  const evolu = use(EvoluContext);

  // useRef to not break "rules-of-hooks"
  const { once } = useRef(options).current;

  if (once) {
    /* eslint-disable react-hooks/rules-of-hooks */
    useEffect(
      // No useSyncExternalStore, no unnecessary updates.
      () => evolu.subscribeQuery(query)(lazyVoid),
      [evolu, query],
    );
    return evolu.getQueryRows(query);
  }

  return useSyncExternalStore(
    useMemo(() => evolu.subscribeQuery(query), [evolu, query]),
    useMemo(() => () => evolu.getQueryRows(query), [evolu, query]),
    () => emptyRows as QueryRows<R>,
    /* eslint-enable react-hooks/rules-of-hooks */
  );
};

// packages/evolu-solid/src/useQuerySubscription.ts
import type { Accessor } from "solid-js";
import {
  Query,
  QueryResult,
  Row,
  emptyRows,
  queryResultFromRows,
} from "@evolu/common";
import * as Function from "effect/Function";
// import { useEffect, useMemo, useRef, useSyncExternalStore } from "react";
import { useEvolu } from "./useEvolu.js";
import { createEffect, createMemo, createSignal } from "solid-js";
import { useSyncExternalStore } from "./useSyncExternalStore.js";

/** Subscribe to {@link Query} {@link QueryResult} changes. */
export const useQuerySubscription = <R extends Row>(
  query: Query<R>,
  options: Partial<{
    /**
     * Just subscribe and get the current value once. Subscribed query will not
     * invoke React Suspense after a mutation.
     */
    readonly once: boolean;
  }> = {},
): Accessor<QueryResult<R>> => {
  const evolu = useEvolu();
  if (options.once) {
    createEffect(
      // No useSyncExternalStore, no unnecessary updates.
      () => evolu.subscribeQuery(query)(Function.constVoid)
    );
    return () => evolu.getQuery(query);
  }
  return useSyncExternalStore(
    () => () => evolu.subscribeQuery(query),
    () => queryResultFromRows(emptyRows()),
  );
};
