// packages/evolu-common-react/src/EvoluProvider.tsx
import { Evolu, DatabaseSchema } from "@evolu/common";
import { ReactNode } from "react";
import { EvoluContext } from "./EvoluContext.js";

export const EvoluProvider = <S extends DatabaseSchema>({
  children,
  value,
}: {
  readonly children?: ReactNode | undefined;
  readonly value: Evolu<S>;
}): JSX.Element => (
  <EvoluContext.Provider value={value as Evolu}>
    {children}
  </EvoluContext.Provider>
);

// packages/solid/src/EvoluProvider.tsx
import { Evolu } from "@evolu/common/evolu";
import { JSX } from "solid-js";
import { EvoluContext } from "./EvoluContext.js";

export const EvoluProvider = (props: {
  readonly children?: JSX.Element;
  readonly value: Evolu<any>;
}): JSX.Element => {
  return (
    <EvoluContext.Provider value={props.value}>
      {props.children}
    </EvoluContext.Provider>
  );
};
