// packages/react/src/useAppOwner.ts
import { AppOwner, constNull } from "@evolu/common";
import { useSyncExternalStore } from "react";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link AppOwner} changes. */
export const useAppOwner = (): AppOwner | null => {
  const evolu = useEvolu();
  return useSyncExternalStore(
    evolu.subscribeAppOwner,
    evolu.getAppOwner,
    constNull,
  );
};

// packages/solid/src/useAppOwner.ts
import { AppOwner } from "@evolu/common";
import { createEffect, createSignal, onCleanup } from "solid-js";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link AppOwner} changes. */
export const useAppOwner = (): (() => AppOwner | null) => {
  const evolu = useEvolu();
  const [appOwner, setAppOwner] = createSignal<AppOwner | null>(
    evolu.getAppOwner(),
  );

  createEffect(() => {
    const unsubscribe = evolu.subscribeAppOwner(() => {
      setAppOwner(evolu.getAppOwner());
    });
    onCleanup(unsubscribe);
  });

  return appOwner;
};
