// packages/react/src/useEvoluError.ts
import { lazyNull, type EvoluError } from "@evolu/common";
import { useSyncExternalStore } from "react";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link EvoluError} changes. */
export const useEvoluError = (): EvoluError | null => {
  const evolu = useEvolu();
  return useSyncExternalStore(evolu.subscribeError, evolu.getError, lazyNull);
};

// packages/solid/src/useEvoluError.ts
import { EvoluError } from "@evolu/common";
import { createEffect, createSignal, onCleanup } from "solid-js";
import { useEvolu } from "./useEvolu.js";

/** Subscribe to {@link EvoluError} changes. */
export const useEvoluError = (): (() => EvoluError | null) => {
  const evolu = useEvolu();
  const [error, setError] = createSignal<EvoluError | null>(evolu.getError());

  createEffect(() => {
    const unsubscribe = evolu.subscribeError(() => {
      setError(evolu.getError());
    });
    onCleanup(unsubscribe);
  });

  return error;
};
