// examples/svelte-vite-pwa/src/App.svelte
<script lang="ts">
  import * as Evolu from "@evolu/common";
  import { syncStateToOwnerSyncStatus } from "@evolu/common/local-first";
  import { appOwnerState, queryState } from "@evolu/svelte";
  import {
    evolu,
    evoluError,
    syncState,
    todosQuery,
    type TodoId,
  } from "./evolu";

  const allTodos = queryState(evolu, () => todosQuery);

  const appOwner = appOwnerState(evolu);

  const { insert, update } = evolu;

  let error = $state(evoluError.get());
  $effect(() =>
    evoluError.subscribe(() => {
      error = evoluError.get();
    }),
  );

  let currentSyncState = $state.raw(syncState.get());
  $effect(() =>
    syncState.subscribe(() => {
      currentSyncState = syncState.get();
    }),
  );

  /**
   * Tells the user when changes can't leave this device, and nothing while
   * sync works. See `OwnerSyncStatus` in `@evolu/common/local-first`.
   */
  const syncMessage = $derived.by(() => {
    // `syncState` lists every database, even other tabs', so this finds the
    // app owner of this one.
    const status = syncStateToOwnerSyncStatus(
      currentSyncState,
      evolu.name,
      evolu.appOwner.id,
    );
    // An app that sells relay quota offers more for a ProtocolQuotaError, then
    // calls `evolu.requestSync(evolu.appOwner.id)`.
    return status.type === "Offline"
      ? "Offline. Your changes are saved on this device."
      : status.type === "Error"
        ? status.error.type === "ProtocolQuotaError"
          ? "Sync is paused because the sync server is full. Your changes are saved on this device."
          : `Sync error: ${status.error.type}. Your changes are saved on this device.`
        : null;
  });

  let newTodoTitle = $state("");
  let showMnemonic = $state(false);

  const handleAddTodo = () => {
    const result = Evolu.NonEmptyTrimmedString100.fromUnknown(newTodoTitle.trim());
    if (!result.ok) {
      alert(Evolu.NonEmptyTrimmedString100.formatError(result.error));
      return;
    }

    insert("todo", { title: result.value });
    newTodoTitle = "";
  };

  const handleToggleCompletedClick = (id: TodoId, isCompleted: boolean) => {
    update("todo", {
      id,
      isCompleted: Evolu.booleanToSqliteBoolean(!isCompleted),
    });
  };

  const handleRenameTodoClick = (id: TodoId, currentTitle: string) => {
    const newTitle = window.prompt("Edit todo", currentTitle);
    if (newTitle == null) return;

    const result = Evolu.NonEmptyTrimmedString100.fromUnknown(newTitle.trim());
    if (!result.ok) {
      alert(Evolu.NonEmptyTrimmedString100.formatError(result.error));
      return;
    }

    update("todo", { id, title: result.value });
  };

  const handleDeleteTodoClick = (id: TodoId) => {
    update("todo", {
      id,
      // Soft delete with isDeleted flag (CRDT-friendly, preserves sync history).
      isDeleted: Evolu.sqliteTrue,
    });
  };

  // Restore owner from mnemonic to sync data across devices.
  const handleRestoreAppOwnerClick = () => {
    const mnemonic = window.prompt("Enter your mnemonic to restore your data:");
    if (mnemonic == null) return;

    const result = Evolu.Mnemonic.fromUnknown(mnemonic.trim());
    if (!result.ok) {
      alert(Evolu.Mnemonic.formatError(result.error));
      // oxlint-disable-next-line eslint/no-useless-return -- Keeps this validation guard correct when owner restoration is implemented.
      return;
    }

    // TODO: Implement secure AppOwner persistence before restoring.
  };

  const handleResetAppOwnerClick = () => {
    if (confirm("Are you sure? This will delete all your local data.")) {
      // TODO: Implement secure AppOwner persistence before resetting.
    }
  };

  const handleDownloadDatabaseClick = () => {
    void evolu.exportDatabase().then((data: Uint8Array<ArrayBuffer>) => {
      const objectUrl = URL.createObjectURL(
        new Blob([data], { type: "application/x-sqlite3" }),
      );
      const link = document.createElement("a");
      link.href = objectUrl;
      link.download = `${evolu.name}.sqlite3`;
      link.click();
      URL.revokeObjectURL(objectUrl);
    });
  };

</script>

<div class="app-container">
  <div class="content-wrapper">
    <div class="header">
      <h1>Minimal Todo App (Evolu + Svelte + Vite + PWA)</h1>
    </div>

    {#if error}
      <p class="evolu-error" role="alert">
        Evolu error: {error.type}. See the console for details.
      </p>
    {/if}

    <!-- Always mounted: screen readers announce changes only in a live region
    that already exists. -->
    <div role="status">
      {#if syncMessage}
        <p class="sync-status">{syncMessage}</p>
      {/if}
    </div>

    <!-- Todos Section -->
    <div class="todos-section">
      <ul class="todos-list">
        {#each allTodos.rows as todo}
          <li class="todo-item">
            <label class="todo-label">
              <input
                type="checkbox"
                checked={!!todo.isCompleted}
                onchange={() =>
                  handleToggleCompletedClick(todo.id, todo.isCompleted === 1)}
                class="todo-checkbox"
              />
              <span class="todo-title" class:completed={todo.isCompleted === 1}>
                {todo.title}
              </span>
            </label>
            <div class="todo-actions">
              <button
                onclick={() => handleRenameTodoClick(todo.id, todo.title)}
                class="action-btn edit-btn"
                title="Edit"
              >
                ✏️
              </button>
              <button
                onclick={() => handleDeleteTodoClick(todo.id)}
                class="action-btn delete-btn"
                title="Delete"
              >
                🗑️
              </button>
            </div>
          </li>
        {/each}
      </ul>

      <div class="add-todo">
        <input
          type="text"
          bind:value={newTodoTitle}
          onkeydown={(e) => {
            if (e.key === "Enter") {
              handleAddTodo();
            }
          }}
          placeholder="Add a new todo..."
          class="todo-input"
        />
        <button onclick={handleAddTodo} class="add-btn">Add</button>
      </div>
    </div>

    <!-- Owner Actions Section -->
    <div class="owner-section">
      <h2>Account</h2>
      <p class="owner-description">
        Todos are stored in local SQLite. When you sync across devices, your
        data is end-to-end encrypted using your mnemonic.
      </p>

      <p class="owner-warning">
        Restore and reset are not implemented yet. Encrypted SQLite requires
        secure persistence and unlocking of the AppOwner secret, such as
        WebAuthn PRF or an external authentication mechanism. Persisting the
        secret directly in browser storage would undermine encryption at rest.
      </p>

      <div class="owner-actions">
        <button
          onclick={() => {
            showMnemonic = !showMnemonic;
          }}
          class="owner-btn full-width"
        >
          {showMnemonic ? "Hide" : "Show"} Mnemonic
        </button>

        {#if showMnemonic && appOwner.current?.mnemonic}
          <div class="mnemonic-display">
            <label class="mnemonic-label" for="mnemonic-textarea">
              Your Mnemonic (keep this safe!)
            </label>
            <textarea
              id="mnemonic-textarea"
              value={appOwner.current.mnemonic}
              readonly
              rows="3"
              class="mnemonic-textarea"
            ></textarea>
          </div>
        {/if}

        <div class="owner-buttons">
          <button onclick={handleRestoreAppOwnerClick} class="owner-btn">
            Restore from Mnemonic
          </button>
          <button onclick={handleResetAppOwnerClick} class="owner-btn">
            Reset All Data
          </button>
          <button onclick={handleDownloadDatabaseClick} class="owner-btn">
            Download Backup
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .evolu-error {
    margin-bottom: 1rem;
    padding: 0.75rem;
    border-radius: 0.375rem;
    background: #fef2f2;
    color: #991b1b;
    font-size: 0.875rem;
  }

  .sync-status {
    margin-bottom: 1rem;
    color: #4b5563;
    font-size: 0.875rem;
  }

  .app-container {
    min-height: 100vh;
    padding: 2rem;
  }

  .content-wrapper {
    max-width: 28rem;
    margin: 0 auto;
  }

  .header {
    margin-bottom: 0.5rem;
    padding-bottom: 1rem;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .header h1 {
    width: 100%;
    text-align: center;
    font-size: 1.25rem;
    font-weight: 600;
    color: #111827;
    margin: 0;
  }

  .todos-section {
    background-color: white;
    border-radius: 0.5rem;
    padding: 1.5rem;
    box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
    border: 1px solid #e5e7eb;
    margin-bottom: 2rem;
  }

  .todos-list {
    list-style: none;
    padding: 0;
    margin: 0 0 1.5rem 0;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .todo-item {
    margin: -0.5rem;
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.5rem;
    border-radius: 0.25rem;
    transition: background-color 0.15s ease;
  }

  .todo-item:hover {
    background-color: #f9fafb;
  }

  .todo-label {
    display: flex;
    flex: 1;
    cursor: pointer;
    align-items: center;
    gap: 0.75rem;
  }

  .todo-checkbox {
    appearance: none;
    border-radius: 0.125rem;
    border: 1px solid #d1d5db;
    background-color: white;
    width: 1rem;
    height: 1rem;
    position: relative;
    cursor: pointer;
  }

  .todo-checkbox:checked {
    border-color: #2563eb;
    background-color: #2563eb;
  }

  .todo-checkbox:checked::after {
    content: "✓";
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    color: white;
    font-size: 0.75rem;
    font-weight: bold;
  }

  .todo-checkbox:focus-visible {
    outline: 2px solid #2563eb;
    outline-offset: 2px;
  }

  .todo-title {
    flex: 1;
    font-size: 0.875rem;
    text-align: left;
    color: #111827;
  }

  .todo-title.completed {
    color: #6b7280;
    text-decoration: line-through;
  }

  .todo-actions {
    display: flex;
    gap: 0.25rem;
  }

  .action-btn {
    padding: 0.25rem;
    color: #9ca3af;
    background: none;
    border: none;
    cursor: pointer;
    border-radius: 0.25rem;
    transition: color 0.15s ease;
    font-size: 1rem;
  }

  .edit-btn:hover {
    color: #2563eb;
  }

  .delete-btn:hover {
    color: #dc2626;
  }

  .add-todo {
    display: flex;
    gap: 0.5rem;
  }

  .todo-input {
    display: block;
    width: 100%;
    border-radius: 0.375rem;
    background-color: white;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    color: #111827;
    border: 1px solid #d1d5db;
    outline: none;
    transition:
      border-color 0.15s ease,
      box-shadow 0.15s ease;
  }

  .todo-input::placeholder {
    color: #9ca3af;
  }

  .todo-input:focus {
    border-color: #4f46e5;
    box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);
  }

  .add-btn {
    padding: 0.5rem 0.75rem;
    font-size: 0.875rem;
    font-weight: 500;
    border-radius: 0.5rem;
    background-color: #2563eb;
    color: white;
    border: none;
    cursor: pointer;
    transition: background-color 0.15s ease;
  }

  .add-btn:hover {
    background-color: #1d4ed8;
  }

  .owner-section {
    background-color: white;
    border-radius: 0.5rem;
    padding: 1.5rem;
    box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
    border: 1px solid #e5e7eb;
  }

  .owner-section h2 {
    margin: 0 0 1rem 0;
    font-size: 1.125rem;
    font-weight: 500;
    color: #111827;
  }

  .owner-description {
    margin: 0 0 1rem 0;
    font-size: 0.875rem;
    color: #6b7280;
  }

  .owner-warning {
    margin: 0 0 1rem 0;
    padding-left: 1rem;
    border-left: 2px solid #fbbf24;
    font-size: 0.875rem;
    color: #6b7280;
  }

  .owner-actions {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .owner-btn {
    padding: 0.5rem 0.75rem;
    font-size: 0.875rem;
    font-weight: 500;
    border-radius: 0.5rem;
    background-color: #f3f4f6;
    color: #374151;
    border: none;
    cursor: pointer;
    transition: background-color 0.15s ease;
  }

  .owner-btn:hover {
    background-color: #e5e7eb;
  }

  .full-width {
    width: 100%;
  }

  .mnemonic-display {
    background-color: #f9fafb;
    padding: 0.75rem;
    border-radius: 0.375rem;
  }

  .mnemonic-label {
    display: block;
    margin-bottom: 0.5rem;
    font-size: 0.75rem;
    font-weight: 500;
    color: #374151;
  }

  .mnemonic-textarea {
    width: 100%;
    border-bottom: 1px solid #d1d5db;
    background-color: white;
    padding: 0.5rem;
    font-family: "Courier New", monospace;
    font-size: 0.75rem;
    border: none;
    border-bottom: 1px solid #d1d5db;
    outline: none;
    resize: none;
  }

  .mnemonic-textarea:focus {
    border-bottom-color: #2563eb;
  }

  .owner-buttons {
    display: flex;
    gap: 0.5rem;
    flex-wrap: wrap;
  }

  .owner-buttons .owner-btn {
    flex: 1;
    min-width: 0;
  }
</style>

// examples/angular-vite-pwa/src/app/app.component.ts
import { Component, inject, signal } from "@angular/core";
import { AppService } from "./app.service";
import { PwaBadgeComponent } from "./pwa-badge.component";

@Component({
  selector: "app-root",
  imports: [PwaBadgeComponent],
  template: `
    <div class="min-h-screen px-8 py-8">
      <div class="mx-auto max-w-md">
        <div class="mb-2 flex items-center justify-between pb-4">
          <h1 class="w-full text-center text-xl font-semibold text-gray-900">
            Minimal Todo App (Evolu + Angular)
          </h1>
        </div>

        @if (appService.evoluError(); as error) {
          <p
            role="alert"
            class="mb-4 rounded-md bg-red-50 p-3 text-sm text-red-800"
          >
            Evolu error: {{ error.type }}. See the console for details.
          </p>
        }

        <!-- Always mounted: screen readers announce changes only in a live
        region that already exists. -->
        <div role="status">
          @if (appService.syncMessage(); as message) {
            <p class="mb-4 text-sm text-gray-600">{{ message }}</p>
          }
        </div>

        @if (appService.isLoading()) {
          <div class="rounded-lg bg-white p-6 shadow-sm ring-1 ring-gray-200">
            <p class="text-sm text-gray-600">Loading todos…</p>
          </div>
        } @else {
          <div class="rounded-lg bg-white p-6 shadow-sm ring-1 ring-gray-200">
            <ol class="mb-6 space-y-2">
              @for (todo of appService.todos(); track todo.id) {
                <li
                  class="-mx-2 flex items-center gap-3 px-2 py-2 hover:bg-gray-50"
                >
                  <label class="flex flex-1 cursor-pointer items-center gap-3">
                    <input
                      type="checkbox"
                      [checked]="todo.isCompleted === 1"
                      (change)="
                        appService.toggleTodo(todo.id, $event.target.checked)
                      "
                      class="col-start-1 row-start-1 appearance-none rounded-sm border border-gray-300 bg-white checked:border-blue-600 checked:bg-blue-600 indeterminate:border-blue-600 indeterminate:bg-blue-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:border-gray-300 disabled:bg-gray-100 disabled:checked:bg-gray-100 forced-colors:appearance-auto"
                    />
                    <span
                      class="flex-1 text-sm"
                      [class]="
                        todo.isCompleted === 1
                          ? 'text-gray-500 line-through'
                          : 'text-gray-900'
                      "
                    >
                      {{ todo.title }}
                    </span>
                  </label>
                  <div class="flex gap-1">
                    <button
                      (click)="handleRenameTodo(todo.id, todo.title)"
                      class="p-1 text-gray-400 transition-colors hover:text-blue-600"
                      title="Edit"
                    >
                      ✏️
                    </button>
                    <button
                      (click)="handleDeleteTodo(todo.id)"
                      class="p-1 text-gray-400 transition-colors hover:text-red-600"
                      title="Delete"
                    >
                      🗑️
                    </button>
                  </div>
                </li>
              }
            </ol>

            <div class="flex gap-2">
              <input
                type="text"
                [value]="newTodoTitle()"
                (input)="setNewTodoTitle($event.target.value)"
                (keydown)="handleKeyDown($event)"
                placeholder="Add a new todo..."
                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
              />
              <button
                type="button"
                (click)="handleAddTodo()"
                class="rounded-lg bg-blue-600 px-3 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
              >
                Add
              </button>
            </div>
          </div>
        }

        <div
          class="mt-8 rounded-lg bg-white p-6 shadow-sm ring-1 ring-gray-200"
        >
          <h2 class="mb-4 text-lg font-medium text-gray-900">Account</h2>
          <p class="mb-4 text-sm text-gray-600">
            Todos are stored in local SQLite. When you sync across devices, your
            data is end-to-end encrypted using your mnemonic.
          </p>

          <div class="space-y-3">
            <button
              type="button"
              (click)="handleShowMnemonic()"
              class="w-full rounded-lg bg-gray-100 px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200"
            >
              {{ showMnemonic() ? "Hide" : "Show" }} Mnemonic
            </button>

            @if (showMnemonic() && appService.mnemonic()) {
              <div class="bg-gray-50 p-3">
                <label class="mb-2 block text-xs font-medium text-gray-700">
                  Your Mnemonic (keep this safe!)
                </label>
                <textarea
                  [value]="appService.mnemonic()"
                  readonly
                  rows="3"
                  class="w-full border-b border-gray-300 bg-white px-2 py-1 font-mono text-xs focus:border-blue-500 focus:outline-none"
                ></textarea>
              </div>
            }

            <div class="flex gap-2">
              <button
                type="button"
                (click)="handleRestoreOwner()"
                class="rounded-lg bg-gray-100 px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200"
              >
                Restore from Mnemonic
              </button>
              <button
                type="button"
                (click)="handleResetOwner()"
                class="rounded-lg bg-gray-100 px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200"
              >
                Reset All Data
              </button>
              <button
                type="button"
                (click)="handleDownloadDatabase()"
                class="rounded-lg bg-gray-100 px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200"
              >
                Download Backup
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <app-pwa-badge></app-pwa-badge>
  `,
})
export class App {
  protected readonly appService = inject(AppService);

  protected readonly showMnemonic = signal(false);
  protected readonly newTodoTitle = signal("");

  /** Todos */

  protected setNewTodoTitle(value: string): void {
    this.newTodoTitle.set(value);
  }

  protected handleKeyDown(event: KeyboardEvent): void {
    if (event.key === "Enter") {
      this.handleAddTodo();
    }
  }

  protected handleAddTodo(): void {
    const title = this.newTodoTitle().trim();
    if (!title) return;

    this.appService.addTodo(title);
    this.newTodoTitle.set("");
  }

  protected handleRenameTodo(id: string, currentTitle: string): void {
    const title = window.prompt("Todo Name", currentTitle);
    if (title == null) return;

    this.appService.renameTodo(id, title);
  }

  protected handleDeleteTodo(id: string): void {
    this.appService.deleteTodo(id);
  }

  /** Footer button handlers */

  protected handleShowMnemonic(): void {
    this.showMnemonic.update((show) => !show);
  }

  protected handleRestoreOwner(): void {
    const mnemonic = window.prompt("Your Mnemonic");
    if (mnemonic == null) return;

    this.appService.restoreFromMnemonic(mnemonic);
  }

  protected handleResetOwner(): void {
    if (confirm("Are you sure? It will delete all your local data.")) {
      this.appService.resetAppOwner();
    }
  }

  protected handleDownloadDatabase(): void {
    void this.appService.downloadDatabase();
  }
}
