// examples/react-vite-pwa/src/PWABadge.tsx
import "./PWABadge.css";

import type { ReactElement } from "react";
import { useRegisterSW } from "virtual:pwa-register/react";

const PWABadge = (): ReactElement => {
  // check for updates every hour
  const period = 60 * 60 * 1000;

  const {
    offlineReady: [offlineReady, setOfflineReady],
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegisteredSW(swUrl, r) {
      if (period <= 0) return;
      if (r?.active?.state === "activated") {
        registerPeriodicSync(period, swUrl, r);
      } else if (r?.installing) {
        r.installing.addEventListener("statechange", (e) => {
          const sw = e.target as ServiceWorker;
          if (sw.state === "activated") registerPeriodicSync(period, swUrl, r);
        });
      }
    },
  });

  const close = (): void => {
    setOfflineReady(false);
    setNeedRefresh(false);
  };

  return (
    <div className="PWABadge" role="alert" aria-labelledby="toast-message">
      {(offlineReady || needRefresh) && (
        <div className="PWABadge-toast">
          <div className="PWABadge-message">
            {offlineReady ? (
              <span id="toast-message">App ready to work offline</span>
            ) : (
              <span id="toast-message">
                New content available, click on reload button to update.
              </span>
            )}
          </div>
          <div className="PWABadge-buttons">
            {needRefresh && (
              <button
                className="PWABadge-toast-button"
                onClick={() => {
                  void updateServiceWorker(true).catch((error: unknown) => {
                    // oxlint-disable-next-line eslint/no-console -- Service worker update failures must remain visible to developers.
                    console.error(error);
                  });
                }}
              >
                Reload
              </button>
            )}
            <button className="PWABadge-toast-button" onClick={() => close()}>
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default PWABadge;

/**
 * This function will register a periodic sync check every hour, you can modify
 * the interval as needed.
 */
const registerPeriodicSync = (
  period: number,
  swUrl: string,
  r: ServiceWorkerRegistration,
): void => {
  if (period <= 0) return;

  setInterval(() => {
    if ("onLine" in navigator && !navigator.onLine) return;

    void (async () => {
      const resp = await fetch(swUrl, {
        cache: "no-store",
        headers: {
          cache: "no-store",
          "cache-control": "no-cache",
        },
      });

      if (resp.status === 200) await r.update();
    })().catch((error: unknown) => {
      // oxlint-disable-next-line eslint/no-console -- Periodic update failures must remain visible to developers.
      console.error(error);
    });
  }, period);
};

// examples/angular-vite-pwa/src/app/pwa-badge.component.ts
import { Component, OnDestroy, signal } from "@angular/core";
import { registerSW } from "virtual:pwa-register";

@Component({
  selector: "app-pwa-badge",
  template: `
    @if (updateAvailable() || offlineReady()) {
      <div
        class="fixed right-4 bottom-4 z-10 max-w-xs border border-gray-300 bg-white p-4 text-sm shadow"
        role="alert"
      >
        <div class="mb-3 text-gray-800">
          @if (offlineReady()) {
            <span>App ready to work offline</span>
          } @else {
            <span>
              New content available, click on reload button to update.
              @if (error()) {
                <br /><small class="text-red-600">{{ error() }}</small>
              }
            </span>
          }
        </div>
        <div class="flex flex-wrap gap-2">
          @if (updateAvailable()) {
            <button
              type="button"
              class="rounded border border-gray-300 px-3 py-1 text-sm hover:bg-gray-100 disabled:opacity-50"
              (click)="handleApplyUpdate()"
            >
              Reload
            </button>
          }
          <button
            type="button"
            class="rounded border border-gray-300 px-3 py-1 text-sm hover:bg-gray-100 disabled:opacity-50"
            (click)="handleDismissUpdate()"
          >
            Close
          </button>
        </div>
      </div>
    }
  `,
})
export class PwaBadgeComponent implements OnDestroy {
  private updateSW?: (reloadPage?: boolean) => Promise<void>;
  private swUpdateTimer?: ReturnType<typeof setInterval>;

  readonly updateAvailable = signal(false);
  readonly offlineReady = signal(false);
  readonly error = signal<string | null>(null);

  constructor() {
    this.initializePWA();
  }

  ngOnDestroy(): void {
    if (this.swUpdateTimer) {
      clearInterval(this.swUpdateTimer);
      this.swUpdateTimer = undefined;
    }
  }

  private setupPeriodicUpdateCheck(
    period: number,
    swUrl: string,
    r: ServiceWorkerRegistration,
  ): void {
    this.swUpdateTimer = setInterval(async () => {
      if ("onLine" in navigator && !navigator.onLine) return;

      const resp = await fetch(swUrl, {
        cache: "no-store",
        headers: {
          cache: "no-store",
          "cache-control": "no-cache",
        },
      });

      if (resp?.status === 200) await r.update();
    }, period);
  }

  private initializePWA(): void {
    // check for updates every hour
    const period = 60 * 60 * 1000;

    this.updateSW = registerSW({
      onNeedRefresh: () => {
        this.updateAvailable.set(true);
      },
      onOfflineReady: () => {
        this.offlineReady.set(true);
      },
      onRegisteredSW: (
        swUrl: string,
        r: ServiceWorkerRegistration | undefined,
      ) => {
        if (period <= 0 || !r) return;

        if (r?.active?.state === "activated") {
          this.setupPeriodicUpdateCheck(period, swUrl, r);
        } else if (r?.installing) {
          r.installing.addEventListener("statechange", (e) => {
            const sw = e.target as ServiceWorker;
            if (sw.state === "activated") {
              this.setupPeriodicUpdateCheck(period, swUrl, r);
            }
          });
        }
      },
    });
  }

  async handleApplyUpdate(): Promise<void> {
    if (!this.updateSW || !this.updateAvailable()) {
      // oxlint-disable-next-line eslint/no-console -- Explains why the requested update cannot run.
      console.log("No updateSW function available!");
      return;
    }

    try {
      await this.updateSW(true);
    } catch (err) {
      this.error.set("Failed to apply update");
      throw err;
    } finally {
      this.updateAvailable.set(false);
    }
  }

  handleDismissUpdate(): void {
    this.updateAvailable.set(false);
    this.offlineReady.set(false);
    this.error.set(null);
  }
}
